import{a as m,S as h,i as d}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const w="48291953-85546cde0c7bc9cda0531770b",L="https://pixabay.com/api/",b=15;let u=1;async function f(o,e=1){try{const n=`${L}?key=${w}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${b}&page=${e}`,s=await m.get(n);if(s.data.hits.length===0)throw new Error("No images found");return u=e,s.data}catch(n){throw n}}function S(){u=1}function q(){return u}function P(){const o=document.querySelector(".gallery");o.innerHTML=""}function y(o){const e=document.querySelector(".gallery"),n=o.map(t=>`
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image" />
        <div class="image-info">
          <p>Likes: <span>${t.likes}</span></p>
          <p>Views: <span>${t.views}</span></p>
          <p>Comments: <span>${t.comments}</span></p>
          <p>Downloads: <span>${t.downloads}</span></p>
        </div>
      </a>
    `).join("");e.insertAdjacentHTML("beforeend",n),new h(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,showCounter:!1}).refresh()}function p(){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}function g(){const o=document.querySelector(".loading");o.style.display="block";const e=document.querySelector(".load-more");e.style.marginBottom="20px"}function c(){const o=document.querySelector(".loading");o.style.display="none"}function i(o){const e=document.querySelector(".load-more");e.style.display=o?"block":"none"}function E(){d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}i(!1);let a="";document.querySelector(".search-form").addEventListener("submit",async function(o){if(o.preventDefault(),a=document.querySelector(".search-input").value.trim(),!!a){S(),P(),g();try{const e=await f(a,1);c(),y(e.hits),i(e.totalHits>e.hits.length)}catch(e){c(),p(),console.error(e)}}});document.querySelector(".load-more").addEventListener("click",async function(){const o=q()+1;g();try{const e=await f(a,o);c(),y(e.hits),o*15>=e.totalHits?(i(!1),E()):i(!0);const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch(e){c(),p(),console.error(e)}});
//# sourceMappingURL=index.js.map
